# frozen_string_literal: true

source 'https://rubygems.org' do
  gem 'base64'
  gem 'bunny', '>= 2.23.0'
  gem 'google-protobuf'
  gem 'json'
  gem 'logger'
  gem 'logging', '~> 2.4'
  gem 'syslog'
  gem 'thread'
  gem 'websocket-driver'
end
