# Use the latest Ruby image as the base image
FROM ruby:3

# Define build arguments with default values
ARG ADAPTER_NAME=default_name
ARG ADAPTER_URL=http://example.com
ARG ADAPTER_TOKEN=default_token
ARG NAME=adapter_dev

# Set environment variables using the build arguments
ENV ADAPTER_NAME=$ADAPTER_NAME \
  ADAPTER_URL=$ADAPTER_URL \
  ADAPTER_TOKEN=$ADAPTER_TOKEN \
  NAME=$NAME

# Set the working directory
WORKDIR /app

# Install useful dev tools
RUN apt-get update && apt-get install -y \
  curl \
  vim \
  git \
  less \
  net-tools \
  iputils-ping \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir $NAME

# Copy the Gemfile and Gemfile.lock into the working directory
COPY . /app/$NAME

# Install dependencies
RUN cd /app/$NAME/ && bundle install

# Default to an interactive shell
CMD ["sh"]
