// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: etcd.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EtcdKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdKey) Reset() {
	*x = EtcdKey{}
	mi := &file_etcd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdKey) ProtoMessage() {}

func (x *EtcdKey) ProtoReflect() protoreflect.Message {
	mi := &file_etcd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdKey.ProtoReflect.Descriptor instead.
func (*EtcdKey) Descriptor() ([]byte, []int) {
	return file_etcd_proto_rawDescGZIP(), []int{0}
}

func (x *EtcdKey) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Dataset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Delimiter     string                 `protobuf:"bytes,3,opt,name=delimiter,proto3" json:"delimiter,omitempty"`
	Tables        []string               `protobuf:"bytes,4,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dataset) Reset() {
	*x = Dataset{}
	mi := &file_etcd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dataset) ProtoMessage() {}

func (x *Dataset) ProtoReflect() protoreflect.Message {
	mi := &file_etcd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dataset.ProtoReflect.Descriptor instead.
func (*Dataset) Descriptor() ([]byte, []int) {
	return file_etcd_proto_rawDescGZIP(), []int{1}
}

func (x *Dataset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dataset) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Dataset) GetDelimiter() string {
	if x != nil {
		return x.Delimiter
	}
	return ""
}

func (x *Dataset) GetTables() []string {
	if x != nil {
		return x.Tables
	}
	return nil
}

var File_etcd_proto protoreflect.FileDescriptor

const file_etcd_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"etcd.proto\x12\adynamos\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n" +
	"\aEtcdKey\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"g\n" +
	"\aDataset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1c\n" +
	"\tdelimiter\x18\x03 \x01(\tR\tdelimiter\x12\x16\n" +
	"\x06tables\x18\x04 \x03(\tR\x06tables2\x80\x01\n" +
	"\x04Etcd\x12<\n" +
	"\bInitEtcd\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12:\n" +
	"\x12GetDatasetMetadata\x12\x10.dynamos.EtcdKey\x1a\x10.dynamos.Dataset\"\x00B'Z%github.com/Jorrit05/DYNAMOS/pkg/protob\x06proto3"

var (
	file_etcd_proto_rawDescOnce sync.Once
	file_etcd_proto_rawDescData []byte
)

func file_etcd_proto_rawDescGZIP() []byte {
	file_etcd_proto_rawDescOnce.Do(func() {
		file_etcd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_etcd_proto_rawDesc), len(file_etcd_proto_rawDesc)))
	})
	return file_etcd_proto_rawDescData
}

var file_etcd_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_etcd_proto_goTypes = []any{
	(*EtcdKey)(nil),       // 0: dynamos.EtcdKey
	(*Dataset)(nil),       // 1: dynamos.Dataset
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_etcd_proto_depIdxs = []int32{
	2, // 0: dynamos.Etcd.InitEtcd:input_type -> google.protobuf.Empty
	0, // 1: dynamos.Etcd.GetDatasetMetadata:input_type -> dynamos.EtcdKey
	2, // 2: dynamos.Etcd.InitEtcd:output_type -> google.protobuf.Empty
	1, // 3: dynamos.Etcd.GetDatasetMetadata:output_type -> dynamos.Dataset
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_etcd_proto_init() }
func file_etcd_proto_init() {
	if File_etcd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_etcd_proto_rawDesc), len(file_etcd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_etcd_proto_goTypes,
		DependencyIndexes: file_etcd_proto_depIdxs,
		MessageInfos:      file_etcd_proto_msgTypes,
	}.Build()
	File_etcd_proto = out.File
	file_etcd_proto_goTypes = nil
	file_etcd_proto_depIdxs = nil
}
