// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: generic.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId    string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	DestinationQueue string                 `protobuf:"bytes,2,opt,name=destination_queue,json=destinationQueue,proto3" json:"destination_queue,omitempty"`
	JobName          string                 `protobuf:"bytes,3,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	ReturnAddress    string                 `protobuf:"bytes,4,opt,name=return_address,json=returnAddress,proto3" json:"return_address,omitempty"`
	JobId            string                 `protobuf:"bytes,5,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RequestMetadata) Reset() {
	*x = RequestMetadata{}
	mi := &file_generic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMetadata) ProtoMessage() {}

func (x *RequestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_generic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMetadata.ProtoReflect.Descriptor instead.
func (*RequestMetadata) Descriptor() ([]byte, []int) {
	return file_generic_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMetadata) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RequestMetadata) GetDestinationQueue() string {
	if x != nil {
		return x.DestinationQueue
	}
	return ""
}

func (x *RequestMetadata) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *RequestMetadata) GetReturnAddress() string {
	if x != nil {
		return x.ReturnAddress
	}
	return ""
}

func (x *RequestMetadata) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ServiceName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceName) Reset() {
	*x = ServiceName{}
	mi := &file_generic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceName) ProtoMessage() {}

func (x *ServiceName) ProtoReflect() protoreflect.Message {
	mi := &file_generic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceName.ProtoReflect.Descriptor instead.
func (*ServiceName) Descriptor() ([]byte, []int) {
	return file_generic_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceName) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

var File_generic_proto protoreflect.FileDescriptor

const file_generic_proto_rawDesc = "" +
	"\n" +
	"\rgeneric.proto\x12\adynamos\x1a\x1bgoogle/protobuf/empty.proto\"\xbe\x01\n" +
	"\x0fRequestMetadata\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12+\n" +
	"\x11destination_queue\x18\x02 \x01(\tR\x10destinationQueue\x12\x19\n" +
	"\bjob_name\x18\x03 \x01(\tR\ajobName\x12%\n" +
	"\x0ereturn_address\x18\x04 \x01(\tR\rreturnAddress\x12\x15\n" +
	"\x06job_id\x18\x05 \x01(\tR\x05jobId\"0\n" +
	"\vServiceName\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName2G\n" +
	"\aGeneric\x12<\n" +
	"\n" +
	"InitTracer\x12\x14.dynamos.ServiceName\x1a\x16.google.protobuf.Empty\"\x00B'Z%github.com/Jorrit05/DYNAMOS/pkg/protob\x06proto3"

var (
	file_generic_proto_rawDescOnce sync.Once
	file_generic_proto_rawDescData []byte
)

func file_generic_proto_rawDescGZIP() []byte {
	file_generic_proto_rawDescOnce.Do(func() {
		file_generic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_generic_proto_rawDesc), len(file_generic_proto_rawDesc)))
	})
	return file_generic_proto_rawDescData
}

var file_generic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_generic_proto_goTypes = []any{
	(*RequestMetadata)(nil), // 0: dynamos.RequestMetadata
	(*ServiceName)(nil),     // 1: dynamos.ServiceName
	(*emptypb.Empty)(nil),   // 2: google.protobuf.Empty
}
var file_generic_proto_depIdxs = []int32{
	1, // 0: dynamos.Generic.InitTracer:input_type -> dynamos.ServiceName
	2, // 1: dynamos.Generic.InitTracer:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_generic_proto_init() }
func file_generic_proto_init() {
	if File_generic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_generic_proto_rawDesc), len(file_generic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_generic_proto_goTypes,
		DependencyIndexes: file_generic_proto_depIdxs,
		MessageInfos:      file_generic_proto_msgTypes,
	}.Build()
	File_generic_proto = out.File
	file_generic_proto_goTypes = nil
	file_generic_proto_depIdxs = nil
}
