# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import generic_pb2 as generic__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class GenericStub(object):
    """The sidecar definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitTracer = channel.unary_unary(
                '/proto.Generic/InitTracer',
                request_serializer=generic__pb2.ServiceName.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class GenericServicer(object):
    """The sidecar definition.
    """

    def InitTracer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenericServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitTracer': grpc.unary_unary_rpc_method_handler(
                    servicer.InitTracer,
                    request_deserializer=generic__pb2.ServiceName.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Generic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Generic(object):
    """The sidecar definition.
    """

    @staticmethod
    def InitTracer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Generic/InitTracer',
            generic__pb2.ServiceName.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
