# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: announcement.proto

require 'google/protobuf'

require 'configuration_pb'
require 'label_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("announcement.proto", :syntax => :proto3) do
    add_message "PluginAdapter.Api.Announcement" do
      optional :name, :string, 1
      optional :configuration, :message, 2, "PluginAdapter.Api.Configuration"
      repeated :labels, :message, 3, "PluginAdapter.Api.Label"
    end
  end
end

module PluginAdapter
  module Api
    Announcement = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Announcement").msgclass
  end
end
