# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: configuration.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("configuration.proto", :syntax => :proto3) do
    add_message "PluginAdapter.Api.Configuration" do
      repeated :items, :message, 1, "PluginAdapter.Api.Configuration.Item"
    end
    add_message "PluginAdapter.Api.Configuration.Item" do
      optional :key, :string, 1
      optional :description, :string, 2
      oneof :type do
        optional :string, :string, 3
        optional :integer, :int64, 4
        optional :float, :float, 5
        optional :boolean, :bool, 6
      end
    end
  end
end

module PluginAdapter
  module Api
    Configuration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Configuration").msgclass
    Configuration::Item = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Configuration.Item").msgclass
  end
end
