# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: label.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("label.proto", :syntax => :proto3) do
    add_message "PluginAdapter.Api.Label" do
      optional :type, :enum, 1, "PluginAdapter.Api.Label.LabelType"
      optional :label, :string, 2
      optional :channel, :string, 3
      repeated :parameters, :message, 4, "PluginAdapter.Api.Label.Parameter"
      optional :timestamp, :uint64, 5
      optional :physical_label, :bytes, 6
      optional :correlation_id, :uint64, 7
    end
    add_message "PluginAdapter.Api.Label.Parameter" do
      optional :name, :string, 1
      optional :value, :message, 2, "PluginAdapter.Api.Label.Parameter.Value"
    end
    add_message "PluginAdapter.Api.Label.Parameter.Value" do
      oneof :type do
        optional :string, :string, 1
        optional :integer, :int64, 2
        optional :decimal, :double, 3
        optional :boolean, :bool, 4
        optional :date, :uint64, 5
        optional :time, :uint64, 9
        optional :array, :message, 6, "PluginAdapter.Api.Label.Parameter.Value.Array"
        optional :struct, :message, 7, "PluginAdapter.Api.Label.Parameter.Value.Hash"
        optional :hash_value, :message, 8, "PluginAdapter.Api.Label.Parameter.Value.Hash"
      end
    end
    add_message "PluginAdapter.Api.Label.Parameter.Value.Array" do
      repeated :values, :message, 1, "PluginAdapter.Api.Label.Parameter.Value"
    end
    add_message "PluginAdapter.Api.Label.Parameter.Value.Hash" do
      repeated :entries, :message, 1, "PluginAdapter.Api.Label.Parameter.Value.Hash.Entry"
    end
    add_message "PluginAdapter.Api.Label.Parameter.Value.Hash.Entry" do
      optional :key, :message, 1, "PluginAdapter.Api.Label.Parameter.Value"
      optional :value, :message, 2, "PluginAdapter.Api.Label.Parameter.Value"
    end
    add_enum "PluginAdapter.Api.Label.LabelType" do
      value :STIMULUS, 0
      value :RESPONSE, 1
    end
  end
end

module PluginAdapter
  module Api
    Label = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Label").msgclass
    Label::Parameter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Label.Parameter").msgclass
    Label::Parameter::Value = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Label.Parameter.Value").msgclass
    Label::Parameter::Value::Array = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Label.Parameter.Value.Array").msgclass
    Label::Parameter::Value::Hash = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Label.Parameter.Value.Hash").msgclass
    Label::Parameter::Value::Hash::Entry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Label.Parameter.Value.Hash.Entry").msgclass
    Label::LabelType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Label.LabelType").enummodule
  end
end
