# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: label.proto

require 'google/protobuf'


descriptor_data = "\n\x0blabel.proto\x12\x11PluginAdapter.Api\"\xa1\x07\n\x05Label\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".PluginAdapter.Api.Label.LabelType\x12\r\n\x05label\x18\x02 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\t\x12\x36\n\nparameters\x18\x04 \x03(\x0b\x32\".PluginAdapter.Api.Label.Parameter\x12\x11\n\ttimestamp\x18\x05 \x01(\x04\x12\x16\n\x0ephysical_label\x18\x06 \x01(\x0c\x12\x16\n\x0e\x63orrelation_id\x18\x07 \x01(\x04\x1a\xa1\x05\n\tParameter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.PluginAdapter.Api.Label.Parameter.Value\x1a\xcc\x04\n\x05Value\x12\x10\n\x06string\x18\x01 \x01(\tH\x00\x12\x11\n\x07integer\x18\x02 \x01(\x03H\x00\x12\x11\n\x07\x64\x65\x63imal\x18\x03 \x01(\x01H\x00\x12\x11\n\x07\x62oolean\x18\x04 \x01(\x08H\x00\x12\x0e\n\x04\x64\x61te\x18\x05 \x01(\x04H\x00\x12\x0e\n\x04time\x18\t \x01(\x04H\x00\x12?\n\x05\x61rray\x18\x06 \x01(\x0b\x32..PluginAdapter.Api.Label.Parameter.Value.ArrayH\x00\x12?\n\x06struct\x18\x07 \x01(\x0b\x32-.PluginAdapter.Api.Label.Parameter.Value.HashH\x00\x12\x43\n\nhash_value\x18\x08 \x01(\x0b\x32-.PluginAdapter.Api.Label.Parameter.Value.HashH\x00\x1a\x41\n\x05\x41rray\x12\x38\n\x06values\x18\x01 \x03(\x0b\x32(.PluginAdapter.Api.Label.Parameter.Value\x1a\xc5\x01\n\x04Hash\x12\x44\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x33.PluginAdapter.Api.Label.Parameter.Value.Hash.Entry\x1aw\n\x05\x45ntry\x12\x35\n\x03key\x18\x01 \x01(\x0b\x32(.PluginAdapter.Api.Label.Parameter.Value\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.PluginAdapter.Api.Label.Parameter.ValueB\x06\n\x04type\"\'\n\tLabelType\x12\x0c\n\x08STIMULUS\x10\x00\x12\x0c\n\x08RESPONSE\x10\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module PluginAdapter
  module Api
    Label = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Label").msgclass
    Label::Parameter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Label.Parameter").msgclass
    Label::Parameter::Value = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Label.Parameter.Value").msgclass
    Label::Parameter::Value::Array = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Label.Parameter.Value.Array").msgclass
    Label::Parameter::Value::Hash = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Label.Parameter.Value.Hash").msgclass
    Label::Parameter::Value::Hash::Entry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Label.Parameter.Value.Hash.Entry").msgclass
    Label::LabelType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Label.LabelType").enummodule
  end
end
