# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

require 'google/protobuf'

require 'label_pb'
require 'announcement_pb'
require 'configuration_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("message.proto", :syntax => :proto3) do
    add_message "PluginAdapter.Api.Message" do
      oneof :type do
        optional :error, :message, 1, "PluginAdapter.Api.Message.Error"
        optional :announcement, :message, 2, "PluginAdapter.Api.Announcement"
        optional :configuration, :message, 3, "PluginAdapter.Api.Configuration"
        optional :label, :message, 4, "PluginAdapter.Api.Label"
        optional :reset, :message, 5, "PluginAdapter.Api.Message.Reset"
        optional :ready, :message, 6, "PluginAdapter.Api.Message.Ready"
      end
    end
    add_message "PluginAdapter.Api.Message.Reset" do
    end
    add_message "PluginAdapter.Api.Message.Ready" do
    end
    add_message "PluginAdapter.Api.Message.Error" do
      optional :message, :string, 1
    end
  end
end

module PluginAdapter
  module Api
    Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Message").msgclass
    Message::Reset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Message.Reset").msgclass
    Message::Ready = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Message.Ready").msgclass
    Message::Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Message.Error").msgclass
  end
end
