# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: announcement.proto

require 'google/protobuf'

require 'configuration_pb'
require 'label_pb'


descriptor_data = "\n\x12\x61nnouncement.proto\x12\x11PluginAdapter.Api\x1a\x13\x63onfiguration.proto\x1a\x0blabel.proto\"\x7f\n\x0c\x41nnouncement\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x37\n\rconfiguration\x18\x02 \x01(\x0b\x32 .PluginAdapter.Api.Configuration\x12(\n\x06labels\x18\x03 \x03(\x0b\x32\x18.PluginAdapter.Api.Labelb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module PluginAdapter
  module Api
    Announcement = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Announcement").msgclass
  end
end
