# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: configuration.proto

require 'google/protobuf'


descriptor_data = "\n\x13\x63onfiguration.proto\x12\x11PluginAdapter.Api\"\xc0\x01\n\rConfiguration\x12\x34\n\x05items\x18\x01 \x03(\x0b\x32%.PluginAdapter.Api.Configuration.Item\x1ay\n\x04Item\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x06string\x18\x03 \x01(\tH\x00\x12\x11\n\x07integer\x18\x04 \x01(\x03H\x00\x12\x0f\n\x05\x66loat\x18\x05 \x01(\x02H\x00\x12\x11\n\x07\x62oolean\x18\x06 \x01(\x08H\x00\x42\x06\n\x04typeb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module PluginAdapter
  module Api
    Configuration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Configuration").msgclass
    Configuration::Item = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Configuration.Item").msgclass
  end
end
