# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etcd.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'


descriptor_data = "\n\netcd.proto\x12\x07\x64ynamos\x1a\x1bgoogle/protobuf/empty.proto\"\x17\n\x07\x45tcdKey\x12\x0c\n\x04path\x18\x01 \x01(\t\"H\n\x07\x44\x61taset\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x11\n\tdelimiter\x18\x03 \x01(\t\x12\x0e\n\x06tables\x18\x04 \x03(\t2\x80\x01\n\x04\x45tcd\x12<\n\x08InitEtcd\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12:\n\x12GetDatasetMetadata\x12\x10.dynamos.EtcdKey\x1a\x10.dynamos.Dataset\"\x00\x42\'Z%github.com/Jorrit05/DYNAMOS/pkg/protob\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Dynamos
  EtcdKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dynamos.EtcdKey").msgclass
  Dataset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dynamos.Dataset").msgclass
end
