# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generic.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'


descriptor_data = "\n\rgeneric.proto\x12\x07\x64ynamos\x1a\x1bgoogle/protobuf/empty.proto\"~\n\x0fRequestMetadata\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\t\x12\x19\n\x11\x64\x65stination_queue\x18\x02 \x01(\t\x12\x10\n\x08job_name\x18\x03 \x01(\t\x12\x16\n\x0ereturn_address\x18\x04 \x01(\t\x12\x0e\n\x06job_id\x18\x05 \x01(\t\"#\n\x0bServiceName\x12\x14\n\x0cservice_name\x18\x01 \x01(\t2G\n\x07Generic\x12<\n\nInitTracer\x12\x14.dynamos.ServiceName\x1a\x16.google.protobuf.Empty\"\x00\x42\'Z%github.com/Jorrit05/DYNAMOS/pkg/protob\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Dynamos
  RequestMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dynamos.RequestMetadata").msgclass
  ServiceName = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dynamos.ServiceName").msgclass
end
