# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microserviceCommunication.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'
require 'google/protobuf/any_pb'
require 'generic_pb'


descriptor_data = "\n\x1fmicroserviceCommunication.proto\x12\x07\x64ynamos\x1a\x1cgoogle/protobuf/struct.proto\x1a\x19google/protobuf/any.proto\x1a\rgeneric.proto\"\xd4\x03\n\x19MicroserviceCommunication\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x14\n\x0crequest_type\x18\x02 \x01(\t\x12%\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x42\n\x08metadata\x18\x04 \x03(\x0b\x32\x30.dynamos.MicroserviceCommunication.MetadataEntry\x12.\n\x10original_request\x18\x05 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x32\n\x10request_metadata\x18\x06 \x01(\x0b\x32\x18.dynamos.RequestMetadata\x12>\n\x06traces\x18\x07 \x03(\x0b\x32..dynamos.MicroserviceCommunication.TracesEntry\x12\x0e\n\x06result\x18\x08 \x01(\x0c\x12\x14\n\x0crouting_data\x18\t \x03(\t\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a-\n\x0bTracesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"/\n\x11\x43ontinueReceiving\x12\x1a\n\x12\x63ontinue_receiving\x18\x01 \x01(\x08\x32\\\n\x0cMicroservice\x12L\n\x08SendData\x12\".dynamos.MicroserviceCommunication\x1a\x1a.dynamos.ContinueReceiving\"\x00\x42\'Z%github.com/Jorrit05/DYNAMOS/pkg/protob\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Dynamos
  MicroserviceCommunication = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dynamos.MicroserviceCommunication").msgclass
  ContinueReceiving = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dynamos.ContinueReceiving").msgclass
end
