# apiVersion: v1
# kind: Pod
# metadata:
#   name: debug
#   namespace: {{ .Values.Namespace }}
# spec:
#   containers:
#   - name: debug
#     image: nicolaka/netshoot
#     command: ['sleep', '3600']
#     stdin: true
#     tty: true
