apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-pvc
  namespace: orchestrator
  annotations:
    "linkerd.io/inject" : disabled
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi

---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-etcd-pvc
  namespace: orchestrator
spec:
  template:
    metadata:
      annotations:
        "linkerd.io/inject": "disabled"
    spec:
      containers:
      - name: init
        image: curlimages/curl
        command:
          - /bin/sh
          - -c
          - |
            base_url="https://raw.githubusercontent.com/Jorrit05/DYNAMOS/new-service-test/configuration/etcd_launch_files"
            files="agreements.json archetype.json datasets.json microservices.json optional_microservices.json requestType.json"

            for file in $files; do
              curl -o /etcd/$file $base_url/$file
            done
        volumeMounts:
        - name: pvc-volume
          mountPath: /etcd
      restartPolicy: OnFailure
      volumes:
      - name: pvc-volume
        persistentVolumeClaim:
          claimName: etcd-pvc
