{
 "title": "Data steward metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active memory UVA - SURF",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"uva\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"surf\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Active memory  - Core, orchestrator",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"core\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"orchestrator\"}) by (namespace)"
    }
   ]
  },
  { "title": "CPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "UVA, SURF, Average CPU usage rate per second (last 5 minutes)",
   "type": "timeseries",
   "description": "For example, a value of 0.4 means that over the last 5 minutes, the pods in the \"surf\" namespace, on average, were using 40% of a single CPU core every second.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"uva\"}[5m])) by (namespace)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"surf\"}[5m])) by (namespace)"
    }
   ]
  },
  {
   "title": "Total System load over CPU Cores",
   "type": "timeseries",
   "description": "A system load of 0.5 means that, on average, the system had 50% of a single CPU core in use during the last 15 minutes. Similarly, a system load of 5 means that the system was using, on average, five CPU cores completely.",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 12 },
   "targets": [
    { "expr": "node_load15" }
   ]
  },
  { "title": "RabbitMQ metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "RabbitMQ connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "targets": [
    { "expr": "sum(rabbitmq_connections)" }
   ]
  },
  {
   "title": "Memory usage Rabbit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=\"core\", pod=~\"rabbitmq.*\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "CPU load RabbitMQ vs entire Core namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"core\", pod=~\"rabbitmq.*\"}[5m])) by (pod)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"core\"}[5m])) by (namespace)"
    }
   ]
  },
  {
   "title": "Rabbit messages ready for delivery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready)"
    }
   ]
  },
  {
   "title": "Published vs. Delivered messages total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 30 },
   "targets": [
    {
     "expr": "sum(rabbitmq_channel_messages_delivered_total)"
    },
    {
     "expr": "sum(rabbitmq_channel_messages_published_total)"
    }
   ]
  },
  {
   "title": "Delivery and publish rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_delivered_total[5m])) by (namespace)"
    },
    {
     "expr": "sum(rate(rabbitmq_channel_messages_published_total[5m])) by (namespace)"
    }
   ]
  }
 ]
}