# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etcd.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\netcd.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"\x17\n\x07\x45tcdKey\x12\x0c\n\x04path\x18\x01 \x01(\t\"H\n\x07\x44\x61taset\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x11\n\tdelimiter\x18\x03 \x01(\t\x12\x0e\n\x06tables\x18\x04 \x03(\t2|\n\x04\x45tcd\x12<\n\x08InitEtcd\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12\x36\n\x12GetDatasetMetadata\x12\x0e.proto.EtcdKey\x1a\x0e.proto.Dataset\"\x00\x42\'Z%github.com/Jorrit05/DYNAMOS/pkg/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'etcd_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z%github.com/Jorrit05/DYNAMOS/pkg/proto'
  _globals['_ETCDKEY']._serialized_start=50
  _globals['_ETCDKEY']._serialized_end=73
  _globals['_DATASET']._serialized_start=75
  _globals['_DATASET']._serialized_end=147
  _globals['_ETCD']._serialized_start=149
  _globals['_ETCD']._serialized_end=273
# @@protoc_insertion_point(module_scope)
