# api_gateway deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api_gateway
  namespace: {{ .Values.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api_gateway
  template:
    metadata:
      labels:
        app: api_gateway
    spec:
      containers:
      - name: api_gateway
        image: jorrit05/dynamos-api_gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: OC_AGENT_HOST
          value: {{ .Values.tracingEndpoint }}
        volumeMounts:
        - name: etcd-startup
          mountPath: /app/etcd
        # resources:
        #   requests:
        #     memory: "128Mi"
        #   limits:
        #     memory: "256Mi"
      - name: sidecar
        image: jorrit05/dynamos-sidecar:latest
        imagePullPolicy: Always
        env:
        - name: AMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbit
              key: password
        - name: AMQ_USER
          value: normal_user
        - name: OC_AGENT_HOST
          value: {{ .Values.tracingEndpoint }}
      volumes:
      - name: etcd-startup
        persistentVolumeClaim:
          claimName: etcd-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: api_gateway
  namespace: {{ .Values.Namespace }}
spec:
  selector:
    app: api_gateway
  ports:
    - name: http-api_gateway-api
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api_gateway-ingress
  namespace: {{ .Values.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: api_gateway.api_gateway.svc.cluster.local
    http:
      paths:
      - pathType: Prefix
        path: "/api/v1"
        backend:
          service:
            name: api_gateway
            port:
              number: 8080
