# apiVersion: networking.istio.io/v1beta1
# kind: VirtualService
# metadata:
#   name: orchestrator-virtualservice
#   namespace: {{ .Values.Namespace }}
# spec:
#   hosts:
#   - "*"
#   gateways:
#   - core/core-gateway
#   http:
#   - match:
#     - uri:
#         prefix: /api/v1/
#     route:
#     - destination:
#         host: orchestrator
#         port:
#           number: 8080
#   # Add additional match and route blocks for the other paths
