apiVersion: apps/v1
kind: Deployment
metadata:
  name: uva
  namespace: uva
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uva
  template:
    metadata:
      labels:
        app: uva
      annotations:
        "linkerd.io/inject" : enabled
    spec:
      serviceAccountName: job-creator-uva
      containers:
      - name: uva
        image: jorrit05/dynamos-agent:{{ .Values.branchNameTag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DATA_STEWARD_NAME
          value: UVA
        - name: OC_AGENT_HOST
          value: {{ .Values.tracingEndpoint }}
        # resources:
        #   requests:
        #     memory: "128Mi"
        #   limits:
        #     memory: "256Mi"
      - name: sidecar
        image: jorrit05/dynamos-sidecar:{{ .Values.branchNameTag }}
        imagePullPolicy: Always
        env:
        - name: AMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbit
              key: password
        - name: AMQ_USER
          value: normal_user
        - name: OC_AGENT_HOST
          value: {{ .Values.tracingEndpoint }}

---

apiVersion: v1
kind: Service
metadata:
  name: uva
  namespace: uva
spec:
  selector:
    app: uva
  ports:
    - name: http-uva-api
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uva-ingress
  namespace: uva
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: uva.uva.svc.cluster.local
    http:
      paths:
      - pathType: Prefix
        path: "/agent/v1/sqlDataRequest/uva"
        backend:
          service:
            name: uva
            port:
              number: 8080