Namespace: orchestrator
hostPath: default
etcdDns: etcd-headless.core.svc.cluster.local
tracingEndpoint: collector.linkerd-jaeger:55678
branchNameTag: "issue/19-improve-dynamos-instability"
dockerArtifactAccount: "poetoec"

