Namespace: orchestrator
hostPath: default
etcdDns: etcd-headless.core.svc.cluster.local
tracingEndpoint: collector.linkerd-jaeger:55678
branchNameTag: sql-query:issue-20-broken-system-tracing
dockerArtifactAccount: "poetoec"

